{{ $containers := list "client" }}
{{- range $container := $containers }}
{{- with index $.Values $container }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $.Release.Name }}-{{ $container }}
  name: {{ $.Release.Name }}-{{ $container }}
spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-{{ $container }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-{{ $container }}
    spec:
      imagePullSecrets:
      - name: {{ $.Release.Name }}-pullsecret
      containers:
      - name: {{ $.Release.Name }}-{{ $container }}
        imagePullPolicy: {{ .container.imagePullPolicy }}
        image: {{ .container.image }}
        ports:
          - containerPort: {{ .container.port }}
        resources: {{- toYaml .container.resources | nindent 10 }}
        volumeMounts:
        {{- range $volumeMount := .container.extraVolumeMounts }}
        - name: {{ $volumeMount.name }}
          mountPath: {{ $volumeMount.mountPath }}
        {{- end }}
      volumes:
      {{- range $volume := .container.extraVolumes }}
      - name: {{ $volume.name }}
        {{- if eq $volume.type "hostPath" }}
        hostPath:
          path: {{ $volume.path }}
        {{- end }}
        {{- if eq $volume.type "configMap" }}
        configMap:
          name: {{ $volume.name }}
        {{- end }}
      {{- end }}
{{- end }}
{{- end }}
