{{- if .Values.docs.container.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "this-is-tobi-docs.docs.fullname" . }}
  labels: {{- include "this-is-tobi-docs.docs.labels" . | nindent 4 }}
data: {{- include "this-is-tobi-docs.containerSecret" .Values.docs.container | indent 2 }}
{{- end -}}
