imageCredentials:
  registry: 
  username: 
  password: 
  email: 

client:
  container:
    image: docker.io/org/image:latest
    port: 8080
    imagePullPolicy: Always
    resources:
      requests:
        memory: "64Mi"
        cpu: "128m"
      limits:
        memory: "128Mi"
        cpu: "256m"
    extraVolumes: []
    extraVolumeMounts: []
  service:
    port: 80
    hostname: client
  ingress:
    enabled: true
    hosts:
      - docs.domain.com
    tls:
      enabled: true
      secretName: ""
    annotations: {}
    labels: {}
