name: Build new aggregated documentation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

env:
  REGISTRY_HOST: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY_NAMESPACE: ${{ github.repository }}
  PLATFORM: linux/amd64,linux/arm64
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: latest
  IMAGE_CONTEXT: ./
  IMAGE_DOCKERFILE: ./Dockerfile
  IMAGE_TARGET: prod
jobs:
  build:
    name: Build, publish and deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun run build:docs -T "$GITHUB_TOKEN"

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Set up QEMU (for multi platform build)
        if: contains(env.PLATFORM, 'arm64')
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a

      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ startsWith(env.IMAGE_NAME, 'ghcr.io') && github.actor || secrets.REGISTRY_USERNAME }}
          password: ${{ startsWith(env.IMAGE_NAME, 'ghcr.io') && github.token || secrets.REGISTRY_PASSWORD }}
          logout: true

      - name: Build and push docker image
        id: build
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: ${{ env.IMAGE_CONTEXT }}
          file: ${{ env.IMAGE_DOCKERFILE }}
          target: ${{ env.IMAGE_TARGET }}
          provenance: false
          sbom: false
          platforms: ${{ env.PLATFORM }}
          outputs: type=image,name=${{ env.IMAGE_NAME }},push-by-digest=true,push=true
          cache-from: ''
          cache-to: ''
          build-args: |
            

      - name: Cleanup old images
        if: ${{ success() }}
        run: |
          ./scripts/purge-ghcr-tags.sh \
            -i "docs" \
            -g "${{ secrets.GITHUB_TOKEN }}" \
            -u "this-is-tobi"

      - name: Deploy docs
        uses: scaleway/action-scw@be2696f261325a78354eda14988c80405f33e082
        with:
          save-config: false
          export-config: false
          version: v2.30.0
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          args: container container deploy ${{ secrets.SCW_CONTAINER_ID }}
