name: Build new aggregated documentation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    name: Build and publish
    uses: this-is-tobi/github-workflows/.github/workflows/build-docker.yml@v0
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      IMAGE_NAME: ghcr.io/${{ github.repository }}
      IMAGE_TAG: ${{ github.sha }}
      IMAGE_DOCKERFILE: ./Dockerfile
      IMAGE_CONTEXT: ./
      IMAGE_TARGET: prod
      LATEST_TAG: true
      BUILD_AMD64: true
      BUILD_ARM64: true
      USE_QEMU: true
    secrets:
      BUILD_SECRETS: |
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Cleanup and deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Cleanup old images
        run: |
          ./scripts/purge-ghcr-tags.sh \
            -i "docs" \
            -g "${{ secrets.GITHUB_TOKEN }}" \
            -u "this-is-tobi"

      - name: Deploy docs
        uses: scaleway/action-scw@be2696f261325a78354eda14988c80405f33e082
        with:
          save-config: false
          export-config: false
          version: v2.30.0
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          args: container container deploy ${{ secrets.SCW_CONTAINER_ID }}
