name: Build new aggregated documentation

on:
  workflow_dispatch:

env:
  REGISTRY_HOST: ${{ vars.REGISTRY_HOST }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  REGISTRY_NAMESPACE: ${{ vars.REGISTRY_NAMESPACE }}
  PLATFORM: linux/amd64,linux/arm64

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3
      - name: Synchronize docs
        run: npm run sync
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU (for multi platform build)
        uses: docker/setup-qemu-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
          logout: true
      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.REGISTRY_HOST }}/${{ env.REGISTRY_NAMESPACE }}:latest
          target: prod
          platforms: ${{ env.PLATFORM }}
          push: true
