name: Build new aggregated documentation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

env:
  REGISTRY_HOST: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY_NAMESPACE: ${{ github.repository }}
  PLATFORM: linux/amd64,linux/arm64

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - name: Synchronize docs
        run: npm run sync

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU (for multi platform build)
        uses: docker/setup-qemu-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
          logout: true

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.REGISTRY_HOST }}/${{ env.REGISTRY_NAMESPACE }}:latest
          target: prod
          platforms: ${{ env.PLATFORM }}
          push: true

      - name: Clean up old images
        if: ${{ success() }}
        run: |
          ./scripts/purge-images.sh \
            -i "docs" \
            -g "${{ secrets.GITHUB_TOKEN }}" \
            -u "this-is-tobi"
